version: '3.3'

services: 
  web:
    restart: always
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file: 
      ./.env
    depends_on: 
      - db
  
  db:
    restart: always
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env_db
  
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6389"
    volumes:
      - redisdata:/data
    depends_on:
      - web
      - db
  
  celery:
    environment:
      - C_FORCE_ROOT=true
    restart: always
    build: ./app
    command: celery -A app worker -B -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler 
    volumes:
      - media_volume:/home/app/web/media
    depends_on:
      - redis
      - db
    env_file:
      - .env
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
  redisdata:
  celery: